"""Lightweight LangChain integration stubs.

This module provides a small abstraction so you can plug in LangChain agents to
transform CLI input into richer template fields. The implementation is intentionally
minimal and will work as a drop-in when you configure API keys and install the
optional dependencies.
"""
from __future__ import annotations

from typing import Dict, Any

try:
    # langchain import is optional at runtime; keep a graceful fallback
    from langchain import LLMChain  # pragma: no cover
    from langchain.llms import OpenAI  # pragma: no cover
except Exception:  # pragma: no cover
    LLMChain = None
    OpenAI = None


def run_agent(input_data: Dict[str, Any]) -> Dict[str, Any]:
    """Run a configurable agent to enrich `input_data`.

    For now the function returns a lightweight transformation (echo) so the CLI
    is usable without API keys. Replace this with a LangChain chain/agent when
    you add credentials and want real AI output.
    """
    # Simple offline placeholder: create a slightly longer description
    title = input_data.get("title", "")
    description = input_data.get("description") or ""

    enriched = {
        "description": description or f"This document titled '{title}' was generated by agentrx.",
    }

    # If langchain is installed and configured, you could run a chain here.
    if LLMChain and OpenAI:  # pragma: no cover
        llm = OpenAI()
        chain = LLMChain(llm=llm, prompt=None)
        # TODO: construct a proper prompt template and run the chain
        # result = chain.run(title)
        # enriched["description"] = result

    return enriched
